export const TABACCO = [
  {
    id: 1,
    image: "./BB-chupa-graper.jpg",
    tabbacoName: "Chupa Graper",
    flavor: "Виноградный чупа-чупс",
    company: "Black Burn",
    line: "Основная",
    strength: "Средняя",
    rating: 5,
    grade: 1,
    review: 122,
    view: 1221,
  },
  {
    id: 2,
    image: "./duftElderBerry.jpeg",
    tabbacoName: "Elder Berry",
    flavor: "Бузина",
    company: "Duft",
    line: "Основная",
    strength: "Средняя",
    rating: 4,
    grade: 2,
    review: 142,
    view: 1441,
  },
  {
    id: 3,
    image: "./SeberoBubbleGum.jpg",
    tabbacoName: "Bubble Gum",
    flavor: "Жевачка",
    company: "Sebero",
    line: "Sebero black",
    strength: "Крепкая",
    rating: 2,
    grade: 5,
    review: 112,
    view: 400,
  },
  {
    id: 4,
    image: "./JentGinAir.jpg",
    tabbacoName: "Gin Air",
    flavor: "Джин",
    company: "Jent",
    line: "Alcohol line",
    strength: "Средняя",
    rating: 5,
    grade: 20,
    review: 2,
    view: 35,
  },
  {
    id: 5,
    image: "./HuliganHardBar.jpg",
    tabbacoName: "Bar",
    flavor: "Барбарис",
    company: "Хулиган",
    line: "Хулиган HARD",
    strength: "Крепкая",
    rating: 3,
    grade: 123,
    review: 11,
    view: 240,
  },
];
